### PR TITLE
feat: orchid watermark

### LINKED ISSUE #9: Replace "Beta" with "Orchid" in logo

### PR DESCRIPTION
**Pull request by tobehn**
Replaced "beta" with "Orchid" in logo

### CODE REVIEW

**Review by kbdharun — APPROVED** [review]
LGTM, Thanks for your contribution.

**Comment by mirkobrombin** [comment]
Let's not merge this yet. Nice work

**Comment by tobehn** [comment]
Do you guys think the color of the watermark also needs to be changed due to #12?
I could do this.

**Comment by mirkobrombin** [comment]
No need but thanks :)

**Pull request merged**
